spring.application.name=ServidorLavadora
server.port=8081
spring.graphql.graphiql.enabled=true
spring.graphql.path=/graphql
spring.graphql.cors.allowed-origins=*
spring.graphql.cors.allowed-methods=GET,POST,OPTIONS
