/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.arezsu.pocvoltia.gui;

import com.arezsu.pocvoltia.model.Electrodomestico;
import com.arezsu.pocvoltia.model.Lavadora;
import com.arezsu.pocvoltia.servicios.ServicioElectrodomestico;
import javax.swing.JOptionPane;

/**
 *
 * @author arezs
 */
  

    public class GUIActualizarLavadora extends javax.swing.JFrame {

        private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIActualizarLavadora.class.getName());

        /**
         * Creates new form GUIBuscarLavadora
         */
        public GUIActualizarLavadora() {
            initComponents();
            setLocationRelativeTo(this);

        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtPrecioBase = new javax.swing.JTextField();
        txtCapacidad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldBuscar = new javax.swing.JTextField();
        btnActualizarLavadora = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtVelCentri = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jcbTecInve = new javax.swing.JCheckBox();
        jButtonBuscar = new javax.swing.JButton();
        jcbMarca = new javax.swing.JComboBox<>();
        jdFecha = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Eliminar Lavadora");

        jLabel1.setText("Fecha de fabricacion:");
        jLabel1.setToolTipText("");

        jLabel2.setText("Codigo:");
        jLabel2.setToolTipText("");

        jLabel3.setText("Marca:");
        jLabel3.setToolTipText("");

        jLabel4.setText("Precio base: ");
        jLabel4.setToolTipText("");

        jLabel5.setText("Capacidad (Kg):");
        jLabel5.setToolTipText("");

        txtCodigo.setEditable(false);
        txtCodigo.setBackground(new java.awt.Color(255, 255, 255));
        txtCodigo.setActionCommand("<Not Set>");
        txtCodigo.setEnabled(false);

        txtPrecioBase.setEditable(false);
        txtPrecioBase.setBackground(new java.awt.Color(255, 255, 255));
        txtPrecioBase.setActionCommand("<Not Set>");

        txtCapacidad.setEditable(false);
        txtCapacidad.setBackground(new java.awt.Color(255, 255, 255));
        txtCapacidad.setActionCommand("<Not Set>");
        txtCapacidad.addActionListener(this::txtCapacidadActionPerformed);

        jLabel7.setText("Kg");
        jLabel7.setToolTipText("");

        jTextFieldBuscar.setToolTipText("Escriba el Codigo de la lavadora");
        jTextFieldBuscar.addActionListener(this::jTextFieldBuscarActionPerformed);

        btnActualizarLavadora.setText("Actualizar");
        btnActualizarLavadora.addActionListener(this::btnActualizarLavadoraActionPerformed);

        jLabel8.setText("Velocidad Centrifugado:");
        jLabel8.setToolTipText("");

        txtVelCentri.addActionListener(this::txtVelCentriActionPerformed);

        jLabel6.setText("Tecnologia Inverter");
        jLabel6.setToolTipText("");

        jcbTecInve.setText("Si");
        jcbTecInve.addActionListener(this::jcbTecInveActionPerformed);

        jButtonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buscar (2).png"))); // NOI18N
        jButtonBuscar.addActionListener(this::jButtonBuscarActionPerformed);

        jcbMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Samsung", "LG", "Whirlpool", "Mabe", "Haceb", "Electrolux", "Bosch", "Haier", "Panasonic", "Frigidaire" }));
        jcbMarca.addActionListener(this::jcbMarcaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addComponent(txtVelCentri, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7))
                    .addComponent(txtPrecioBase, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jcbTecInve))
                    .addComponent(jcbMarca, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jdFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(btnActualizarLavadora)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcbMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jdFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPrecioBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtVelCentri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jcbTecInve))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnActualizarLavadora)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBuscarActionPerformed
        jButtonBuscarActionPerformed(evt);
    }//GEN-LAST:event_jTextFieldBuscarActionPerformed

    private void btnActualizarLavadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarLavadoraActionPerformed
        try {
            int codigo = Integer.parseInt(txtCodigo.getText().trim());

            Electrodomestico e = ServicioElectrodomestico.buscarElectrodomesticoPorCodigo(codigo);

            if (e != null && e instanceof Lavadora) {
                Lavadora lav = (Lavadora) e;

                lav.setMarca(jcbMarca.getSelectedItem().toString());
                if (jdFecha.getDate() != null) {
                    lav.setFechaFabricacion(new java.sql.Date(jdFecha.getDate().getTime()).toLocalDate());
                }
                lav.setPrecioBase(Double.parseDouble(txtPrecioBase.getText().trim()));
                lav.setCapacidadCargaKilos(Double.parseDouble(txtCapacidad.getText().trim()));
                lav.setVelocidadCentrifugadoRPM(Integer.parseInt(txtVelCentri.getText().trim()));
                lav.setTecnologiaInverter(jcbTecInve.isSelected());

                JOptionPane.showMessageDialog(this, "¡Lavadora actualizada con éxito!", "Actualizado", JOptionPane.INFORMATION_MESSAGE);

            } else {
                JOptionPane.showMessageDialog(this, "No se encontró una lavadora para actualizar.", "Error", JOptionPane.WARNING_MESSAGE);
            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Por favor, verifica que los campos numéricos tengan un formato válido.", "Error de formato", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error al actualizar: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        
        }    }//GEN-LAST:event_btnActualizarLavadoraActionPerformed

    private void txtCapacidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCapacidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCapacidadActionPerformed

    private void txtVelCentriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVelCentriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVelCentriActionPerformed

    private void jcbTecInveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTecInveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbTecInveActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
try {
            int codigo = Integer.parseInt(jTextFieldBuscar.getText().trim());
            
            Electrodomestico e = ServicioElectrodomestico.buscarElectrodomesticoPorCodigo(codigo);

    if (e != null && e instanceof Lavadora) {
                Lavadora lav = (Lavadora) e;

                txtCodigo.setText(String.valueOf(lav.getCodigo()));
                jcbMarca.setSelectedItem(lav.getMarca());
                if (lav.getFechaFabricacion() != null) {
                    jdFecha.setDate(java.sql.Date.valueOf(lav.getFechaFabricacion()));
                }
                txtPrecioBase.setText(String.valueOf(lav.getPrecioBase()));
                txtCapacidad.setText(String.valueOf(lav.getCapacidadCargaKilos()));
                txtVelCentri.setText(String.valueOf(lav.getVelocidadCentrifugadoRPM()));
                jcbTecInve.setSelected(lav.isTecnologiaInverter());

                JOptionPane.showMessageDialog(this, "¡Lavadora encontrada y cargada!", "Éxito", JOptionPane.INFORMATION_MESSAGE);

            } else {
                JOptionPane.showMessageDialog(this, "No se encontró una lavadora registrada con ese código.", "Error", JOptionPane.WARNING_MESSAGE);
            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Por favor, ingresa un código numérico válido.", "Error de formato", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error al buscar: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jcbMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbMarcaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUIActualizarLavadora().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarLavadora;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextFieldBuscar;
    private javax.swing.JComboBox<String> jcbMarca;
    private javax.swing.JCheckBox jcbTecInve;
    private com.toedter.calendar.JDateChooser jdFecha;
    private javax.swing.JTextField txtCapacidad;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtPrecioBase;
    private javax.swing.JTextField txtVelCentri;
    // End of variables declaration//GEN-END:variables
}
