/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.arezsu.pocvoltia.gui;

import com.arezsu.pocvoltia.model.Electrodomestico;
import com.arezsu.pocvoltia.model.ProgramaLavado;
import com.arezsu.pocvoltia.servicios.ServicioProgramaLavado;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author arezs
 */
  

    public class GUIEliminarProgramaLavado extends javax.swing.JFrame {

        private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIEliminarProgramaLavado.class.getName());

        /**
         * Creates new form GUIAddProgramaLavado
         */
        public GUIEliminarProgramaLavado() {
            initComponents();
            setLocationRelativeTo(this);
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtMinMin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcbProgLav = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMinMax = new javax.swing.JTextField();
        jTextFieldBuscar = new javax.swing.JTextField();
        btnDelProgLav = new javax.swing.JButton();
        jButtonBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Eliminar Programa Lavado");

        txtMinMin.setEditable(false);
        txtMinMin.setToolTipText("Minimo");
        txtMinMin.setEnabled(false);
        txtMinMin.addActionListener(this::txtMinMinActionPerformed);

        jLabel2.setText("Nombre:");
        jLabel2.setToolTipText("");

        jLabel3.setText("Minutos:");
        jLabel3.setToolTipText("");

        jcbProgLav.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rápido / Express", "Diario / Mixto", "Algodón / Normal", "Sintéticos", "Delicados / Lana", "Eco", "Deportivo", "Intensivo / Manchas" }));
        jcbProgLav.setEnabled(false);

        jLabel4.setText("Codigo");
        jLabel4.setToolTipText("");

        txtId.setEditable(false);
        txtId.setEnabled(false);
        txtId.addActionListener(this::txtIdActionPerformed);

        jLabel5.setText("--");
        jLabel5.setToolTipText("");

        txtMinMax.setEditable(false);
        txtMinMax.setToolTipText("Maximos");
        txtMinMax.setEnabled(false);
        txtMinMax.addActionListener(this::txtMinMaxActionPerformed);

        jTextFieldBuscar.setToolTipText("Escriba el Codigo de la lavadora");
        jTextFieldBuscar.addActionListener(this::jTextFieldBuscarActionPerformed);

        btnDelProgLav.setText("Borrar");
        btnDelProgLav.addActionListener(this::btnDelProgLavActionPerformed);

        jButtonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buscar (2).png"))); // NOI18N
        jButtonBuscar.addActionListener(this::jButtonBuscarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcbProgLav, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtMinMin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMinMax, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtId)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(btnDelProgLav)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jcbProgLav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMinMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtMinMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDelProgLav)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMinMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMinMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMinMinActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtMinMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMinMaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMinMaxActionPerformed

    private void jTextFieldBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBuscarActionPerformed

    }//GEN-LAST:event_jTextFieldBuscarActionPerformed

    private void btnDelProgLavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelProgLavActionPerformed
        try {
            // 1. Tomamos el código (en ProgramaLavado el ID es un String)
            String idAEliminar = txtId.getText().trim();

            if (idAEliminar.isEmpty()) {
                throw new IllegalArgumentException("Debe ingresar el código del programa a eliminar.");
            }

            // 2. Llamamos al método de eliminar de tu Servicio
            boolean eliminado = ServicioProgramaLavado.eliminarProgramaLavado(idAEliminar);

            if (eliminado) {
                JOptionPane.showMessageDialog(this, "¡Programa de lavado eliminado con éxito!", "Eliminado", JOptionPane.INFORMATION_MESSAGE);

                // 3. Limpiamos los campos adaptados a ProgramaLavado
                txtId.setText("");
                jTextFieldBuscar.setText(""); // Por si usabas el buscador de arriba
                if (jcbProgLav.getItemCount() > 0) {
                    jcbProgLav.setSelectedIndex(0); // Resetea el combo al primer elemento
                }
                txtMinMin.setText("");
                txtMinMax.setText("");

            } else {
                JOptionPane.showMessageDialog(this, "No se encontró ningún programa registrado con ese código.", "Error", JOptionPane.WARNING_MESSAGE);
            }

        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error de validación", JOptionPane.WARNING_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        
        }    }//GEN-LAST:event_btnDelProgLavActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        try {
            // CAMBIA txtId por jTextFieldBuscar aquí:
            String id = jTextFieldBuscar.getText().trim();

            if (id.isEmpty()) {
                throw new IllegalArgumentException("Debe ingresar el código (ID) del programa a buscar.");
            }

            ProgramaLavado programa = ServicioProgramaLavado.buscarProgramaPorId(id);

            if (programa != null) {
                // Y si quieres que al buscar también se llene el txtId o los demás campos, puedes hacerlo:
                txtId.setText(programa.getId());
                jcbProgLav.setSelectedItem(programa.getNombre());
                txtMinMin.setText(String.valueOf(programa.getMinMinutos()));
                txtMinMax.setText(String.valueOf(programa.getMaxMinutos()));
                javax.swing.JOptionPane.showMessageDialog(this, "¡Programa encontrado con éxito!");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "No se encontró ningún programa registrado con ese código.", "No encontrado", javax.swing.JOptionPane.WARNING_MESSAGE);
            }

        } catch (IllegalArgumentException e) {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(), "Error de validación", javax.swing.JOptionPane.WARNING_MESSAGE);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUIEliminarProgramaLavado().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelProgLav;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextFieldBuscar;
    private javax.swing.JComboBox<String> jcbProgLav;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtMinMax;
    private javax.swing.JTextField txtMinMin;
    // End of variables declaration//GEN-END:variables
}
