/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.arezsu.pocvoltia.gui;

import com.arezsu.pocvoltia.model.Electrodomestico;
import com.arezsu.pocvoltia.model.Lavadora;
import com.arezsu.pocvoltia.model.Nevera;
import com.arezsu.pocvoltia.servicios.ServicioElectrodomestico;
import javax.swing.JOptionPane;

/**
 *
 * @author arezs
 */
public class GUIEliminarNevera extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIEliminarNevera.class.getName());

    /**
     * Creates new form GUIBuscarLavadora
     */
    public GUIEliminarNevera() {
        initComponents();
        setLocationRelativeTo(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtPrecioBase = new javax.swing.JTextField();
        txtCapacidad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldBuscar = new javax.swing.JTextField();
        btnEliminarNevera = new javax.swing.JButton();
        txtNumPuertas = new javax.swing.JTextField();
        jcbDispenAgua = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButtonBuscar = new javax.swing.JButton();
        jcbMarca = new javax.swing.JComboBox<>();
        jdFecha = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Borrar Nevera");

        jLabel1.setText("Fecha de fabricacion:");
        jLabel1.setToolTipText("");

        jLabel2.setText("Codigo:");
        jLabel2.setToolTipText("");

        jLabel3.setText("Marca:");
        jLabel3.setToolTipText("");

        jLabel4.setText("Precio base: ");
        jLabel4.setToolTipText("");

        jLabel5.setText("Volumen:");
        jLabel5.setToolTipText("");

        txtCodigo.setEditable(false);
        txtCodigo.setActionCommand("<Not Set>");
        txtCodigo.setEnabled(false);

        txtPrecioBase.setEditable(false);
        txtPrecioBase.setActionCommand("<Not Set>");
        txtPrecioBase.setEnabled(false);

        txtCapacidad.setEditable(false);
        txtCapacidad.setActionCommand("<Not Set>");
        txtCapacidad.setEnabled(false);
        txtCapacidad.addActionListener(this::txtCapacidadActionPerformed);

        jLabel7.setText("L");
        jLabel7.setToolTipText("");

        jTextFieldBuscar.setToolTipText("Escriba el Codigo de la lavadora");
        jTextFieldBuscar.addActionListener(this::jTextFieldBuscarActionPerformed);

        btnEliminarNevera.setText("Eliminar");
        btnEliminarNevera.addActionListener(this::btnEliminarNeveraActionPerformed);

        txtNumPuertas.setEnabled(false);
        txtNumPuertas.addActionListener(this::txtNumPuertasActionPerformed);

        jcbDispenAgua.setText("Si");
        jcbDispenAgua.setEnabled(false);
        jcbDispenAgua.addActionListener(this::jcbDispenAguaActionPerformed);

        jLabel8.setText("Numero de puertas");
        jLabel8.setToolTipText("");

        jLabel6.setText("Dispensador de agua");
        jLabel6.setToolTipText("");

        jButtonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buscar (2).png"))); // NOI18N
        jButtonBuscar.addActionListener(this::jButtonBuscarActionPerformed);

        jcbMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Samsung", "LG", "Whirlpool", "Mabe", "Haceb", "Electrolux", "Bosch", "Haier", "Panasonic", "Frigidaire" }));
        jcbMarca.setEnabled(false);
        jcbMarca.addActionListener(this::jcbMarcaActionPerformed);

        jdFecha.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7))
                                    .addComponent(txtCodigo)
                                    .addComponent(jdFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jcbMarca, 0, 139, Short.MAX_VALUE)
                                    .addComponent(txtPrecioBase)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcbDispenAgua)
                                    .addComponent(txtNumPuertas)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(btnEliminarNevera)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jdFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPrecioBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtNumPuertas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbDispenAgua)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btnEliminarNevera)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBuscarActionPerformed
        jButtonBuscarActionPerformed(evt);
    }//GEN-LAST:event_jTextFieldBuscarActionPerformed

    private void txtCapacidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCapacidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCapacidadActionPerformed

    private void btnEliminarNeveraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarNeveraActionPerformed
        try {
            // 1. Tomamos el código de la caja de texto
            int codigoAEliminar = Integer.parseInt(txtCodigo.getText().trim());

            // 2. Llamamos al método de eliminar de tu Servicio
            boolean eliminado = ServicioElectrodomestico.eliminarElectrodomestico(codigoAEliminar);

            if (eliminado) {
                JOptionPane.showMessageDialog(this, "¡Nevera eliminada con éxito!", "Eliminado", JOptionPane.INFORMATION_MESSAGE);

                // 3. Limpiamos los campos y controles correctamente adaptados a Lavadora
                txtCodigo.setText("");
                if (jcbMarca.getItemCount() > 0) {
                    jcbMarca.setSelectedIndex(0); // Resetea el combo de marca al primer elemento
                }
                jdFecha.setDate(null); // Limpia el JDateChooser
                txtPrecioBase.setText("");
                txtCapacidad.setText("");
                txtNumPuertas.setText("");
                jcbDispenAgua.setSelected(false); // Desmarca el checkbox de tecnología inverter

            } else {
                JOptionPane.showMessageDialog(this, "No se encontró ninguna nevadora registrada con ese código.", "Error", JOptionPane.WARNING_MESSAGE);
            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Por favor, ingresa un código numérico válido.", "Error de formato", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnEliminarNeveraActionPerformed

    private void txtNumPuertasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumPuertasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumPuertasActionPerformed

    private void jcbDispenAguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbDispenAguaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbDispenAguaActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        try {
            int codigoBuscado = Integer.parseInt(jTextFieldBuscar.getText().trim());

            Electrodomestico e = ServicioElectrodomestico.buscarElectrodomesticoPorCodigo(codigoBuscado);

            if (e != null && e instanceof Nevera) {
                Nevera nev = (Nevera) e;

                txtCodigo.setText(String.valueOf(nev.getCodigo()));

                jcbMarca.setSelectedItem(nev.getMarca());

                txtPrecioBase.setText(String.valueOf(nev.getPrecioBase()));
                txtCapacidad.setText(String.valueOf(nev.getVolumenLitros()));
                txtNumPuertas.setText(String.valueOf(nev.getNumeroPuertas()));
                jcbDispenAgua.setSelected(nev.isDispensadorAgua());

                JOptionPane.showMessageDialog(this, "¡Lavadora encontrada y cargada!", "Éxito", JOptionPane.INFORMATION_MESSAGE);

            } else if (e != null) {
                JOptionPane.showMessageDialog(this, "El código pertenece a otro tipo de electrodoméstico, no a una nevadora.", "Aviso", JOptionPane.WARNING_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "No existe ningún electrodoméstico registrado con ese código.", "No encontrado", JOptionPane.ERROR_MESSAGE);
            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Por favor, ingresa un código numérico válido.", "Error de formato", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jcbMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbMarcaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUIEliminarNevera().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarNevera;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextFieldBuscar;
    private javax.swing.JCheckBox jcbDispenAgua;
    private javax.swing.JComboBox<String> jcbMarca;
    private com.toedter.calendar.JDateChooser jdFecha;
    private javax.swing.JTextField txtCapacidad;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNumPuertas;
    private javax.swing.JTextField txtPrecioBase;
    // End of variables declaration//GEN-END:variables
}
