/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.arezsu.pocvoltia.gui;

import com.arezsu.pocvoltia.model.Electrodomestico;
import com.arezsu.pocvoltia.model.Lavadora;
import com.arezsu.pocvoltia.model.ProgramaLavado;
import com.arezsu.pocvoltia.servicios.ServicioElectrodomestico;
import com.arezsu.pocvoltia.servicios.ServicioProgramaLavado;
import java.util.Map;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author UNIBAGUE
 */
public class GUIListarProgramaLavado extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIListarProgramaLavado.class.getName());

    /**
     * Creates new form GUIListarDocente
     */
    public GUIListarProgramaLavado() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblProgramaLav = new javax.swing.JTable();
        btnListarProgLav = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Listar Programas Lavados");
        setBackground(new java.awt.Color(255, 255, 153));
        setResizable(false);

        tblProgramaLav.setBackground(new java.awt.Color(204, 204, 255));
        tblProgramaLav.setBorder(new javax.swing.border.MatteBorder(null));
        tblProgramaLav.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "MinMinuto", "MaxMinuto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblProgramaLav);

        btnListarProgLav.setText("Listar");
        btnListarProgLav.addActionListener(this::btnListarProgLavActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnListarProgLav, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnListarProgLav)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListarProgLavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarProgLavActionPerformed
        Map<String, ProgramaLavado> programas = ServicioProgramaLavado.getProgramasLavado();

        DefaultTableModel modelo = (DefaultTableModel) tblProgramaLav.getModel();
        modelo.setRowCount(0); // Limpia la tabla antes de cargar para evitar duplicados

        for (Map.Entry<String, ProgramaLavado> entry : programas.entrySet()) {
            String id = entry.getKey();
            ProgramaLavado prog = entry.getValue();

            Object[] fila = new Object[]{
                id,
                prog.getNombre(),
                prog.getMinMinutos(),
                prog.getMaxMinutos()
            };

            modelo.addRow(fila);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnListarProgLavActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUIListarProgramaLavado().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnListarProgLav;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProgramaLav;
    // End of variables declaration//GEN-END:variables
}
