/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.arezsu.pocvoltia.gui;

import javax.swing.JOptionPane;

/**
 *
 * @author UNIBAGUE
 */
public class GUIPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIPrincipal.class.getName());

    /**
     * Creates new form GUIPrincipal
     */
    public GUIPrincipal() {
        initComponents();
        setLocationRelativeTo(this);
        com.arezsu.pocvoltia.util.SoundPlayer.playSound("click.wav");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuAddLav = new javax.swing.JMenuItem();
        jMenuBuscarLav = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuListLav = new javax.swing.JMenuItem();
        jMenuDelLav = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuAddNev = new javax.swing.JMenuItem();
        jMenuBuscNev = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuListNev = new javax.swing.JMenuItem();
        jMenuDelNev = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal");
        setBackground(new java.awt.Color(255, 255, 153));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));

        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gemini_Generated_Image_ucgrmtucg.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 255));

        jMenu1.setBackground(new java.awt.Color(244, 246, 247));
        jMenu1.setForeground(new java.awt.Color(51, 51, 51));
        jMenu1.setText("Archivo");
        jMenu1.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N
        jMenu1.setHideActionText(true);

        jMenuItem1.setBackground(new java.awt.Color(244, 246, 247));
        jMenuItem1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jMenuItem1.setForeground(new java.awt.Color(51, 51, 51));
        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu5.setBackground(new java.awt.Color(244, 246, 247));
        jMenu5.setForeground(new java.awt.Color(51, 51, 51));
        jMenu5.setText("Programa Lavado");

        jMenuItem4.setBackground(new java.awt.Color(244, 246, 247));
        jMenuItem4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jMenuItem4.setForeground(new java.awt.Color(51, 51, 51));
        jMenuItem4.setText("Adicionar Programa Lavado");
        jMenuItem4.addActionListener(this::jMenuItem4ActionPerformed);
        jMenu5.add(jMenuItem4);

        jMenuItem5.setBackground(new java.awt.Color(244, 246, 247));
        jMenuItem5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jMenuItem5.setForeground(new java.awt.Color(51, 51, 51));
        jMenuItem5.setText("Actualizar Programa Lavado");
        jMenuItem5.addActionListener(this::jMenuItem5ActionPerformed);
        jMenu5.add(jMenuItem5);

        jMenuItem6.setBackground(new java.awt.Color(244, 246, 247));
        jMenuItem6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jMenuItem6.setForeground(new java.awt.Color(51, 51, 51));
        jMenuItem6.setText("Buscar Programa Lavado");
        jMenuItem6.addActionListener(this::jMenuItem6ActionPerformed);
        jMenu5.add(jMenuItem6);

        jMenuItem10.setBackground(new java.awt.Color(244, 246, 247));
        jMenuItem10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jMenuItem10.setForeground(new java.awt.Color(51, 51, 51));
        jMenuItem10.setText("Borrar Programa Lavado");
        jMenuItem10.addActionListener(this::jMenuItem10ActionPerformed);
        jMenu5.add(jMenuItem10);

        jMenuItem7.setBackground(new java.awt.Color(244, 246, 247));
        jMenuItem7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jMenuItem7.setForeground(new java.awt.Color(51, 51, 51));
        jMenuItem7.setText("Listar Programa Lavado");
        jMenuItem7.addActionListener(this::jMenuItem7ActionPerformed);
        jMenu5.add(jMenuItem7);

        jMenuBar1.add(jMenu5);

        jMenu3.setBackground(new java.awt.Color(244, 246, 247));
        jMenu3.setForeground(new java.awt.Color(51, 51, 51));
        jMenu3.setText("Lavadora");
        jMenu3.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N

        jMenuAddLav.setBackground(new java.awt.Color(244, 246, 247));
        jMenuAddLav.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jMenuAddLav.setForeground(new java.awt.Color(51, 51, 51));
        jMenuAddLav.setText("Adicionar Lavadora");
        jMenuAddLav.addActionListener(this::jMenuAddLavActionPerformed);
        jMenu3.add(jMenuAddLav);

        jMenuBuscarLav.setBackground(new java.awt.Color(244, 246, 247));
        jMenuBuscarLav.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jMenuBuscarLav.setForeground(new java.awt.Color(51, 51, 51));
        jMenuBuscarLav.setText("Buscar Lavadora");
        jMenuBuscarLav.addActionListener(this::jMenuBuscarLavActionPerformed);
        jMenu3.add(jMenuBuscarLav);

        jMenuItem2.setBackground(new java.awt.Color(244, 246, 247));
        jMenuItem2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jMenuItem2.setForeground(new java.awt.Color(51, 51, 51));
        jMenuItem2.setText("Actualizar Lavadora");
        jMenuItem2.addActionListener(this::jMenuItem2ActionPerformed);
        jMenu3.add(jMenuItem2);

        jMenuListLav.setBackground(new java.awt.Color(244, 246, 247));
        jMenuListLav.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jMenuListLav.setForeground(new java.awt.Color(51, 51, 51));
        jMenuListLav.setText("Listar Lavadora");
        jMenuListLav.addActionListener(this::jMenuListLavActionPerformed);
        jMenu3.add(jMenuListLav);

        jMenuDelLav.setBackground(new java.awt.Color(244, 246, 247));
        jMenuDelLav.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jMenuDelLav.setForeground(new java.awt.Color(51, 51, 51));
        jMenuDelLav.setText("Eliminar Lavadora");
        jMenuDelLav.addActionListener(this::jMenuDelLavActionPerformed);
        jMenu3.add(jMenuDelLav);

        jMenuBar1.add(jMenu3);

        jMenu4.setBackground(new java.awt.Color(244, 246, 247));
        jMenu4.setForeground(new java.awt.Color(51, 51, 51));
        jMenu4.setText("Nevera");
        jMenu4.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N

        jMenuAddNev.setBackground(new java.awt.Color(244, 246, 247));
        jMenuAddNev.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jMenuAddNev.setForeground(new java.awt.Color(51, 51, 51));
        jMenuAddNev.setText("Adicionar Nevera");
        jMenuAddNev.addActionListener(this::jMenuAddNevActionPerformed);
        jMenu4.add(jMenuAddNev);

        jMenuBuscNev.setBackground(new java.awt.Color(244, 246, 247));
        jMenuBuscNev.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jMenuBuscNev.setForeground(new java.awt.Color(51, 51, 51));
        jMenuBuscNev.setText("Buscar Nevera");
        jMenuBuscNev.addActionListener(this::jMenuBuscNevActionPerformed);
        jMenu4.add(jMenuBuscNev);

        jMenuItem3.setBackground(new java.awt.Color(244, 246, 247));
        jMenuItem3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jMenuItem3.setForeground(new java.awt.Color(51, 51, 51));
        jMenuItem3.setText("Actualizar Lavadora");
        jMenuItem3.addActionListener(this::jMenuItem3ActionPerformed);
        jMenu4.add(jMenuItem3);

        jMenuListNev.setBackground(new java.awt.Color(244, 246, 247));
        jMenuListNev.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jMenuListNev.setForeground(new java.awt.Color(51, 51, 51));
        jMenuListNev.setText("Listar Nevera");
        jMenuListNev.addActionListener(this::jMenuListNevActionPerformed);
        jMenu4.add(jMenuListNev);

        jMenuDelNev.setBackground(new java.awt.Color(244, 246, 247));
        jMenuDelNev.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jMenuDelNev.setForeground(new java.awt.Color(51, 51, 51));
        jMenuDelNev.setText("Eliminar Nevera");
        jMenuDelNev.addActionListener(this::jMenuDelNevActionPerformed);
        jMenu4.add(jMenuDelNev);

        jMenuBar1.add(jMenu4);

        jMenu2.setBackground(new java.awt.Color(244, 246, 247));
        jMenu2.setForeground(new java.awt.Color(51, 51, 51));
        jMenu2.setText("Ayuda");
        jMenu2.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N

        jMenuItem8.setText("Acerca de");
        jMenuItem8.addActionListener(this::jMenuItem8ActionPerformed);
        jMenu2.add(jMenuItem8);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuAddLavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAddLavActionPerformed
        GUIAddLavadora gui = new GUIAddLavadora();
        gui.setVisible(true);
    }//GEN-LAST:event_jMenuAddLavActionPerformed

    private void jMenuListLavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuListLavActionPerformed
        GUIListarLavadora gui = new GUIListarLavadora();
        gui.setVisible(true);
    }//GEN-LAST:event_jMenuListLavActionPerformed

    private void jMenuAddNevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAddNevActionPerformed
        GUIAddNevera gui = new GUIAddNevera();
        gui.setVisible(true);
    }//GEN-LAST:event_jMenuAddNevActionPerformed

    private void jMenuListNevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuListNevActionPerformed
        GUIListarNevera gui = new GUIListarNevera();
        gui.setVisible(true);

    }//GEN-LAST:event_jMenuListNevActionPerformed

    private void jMenuBuscarLavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuBuscarLavActionPerformed
        GUIBuscarLavadora gui = new GUIBuscarLavadora();
        gui.setVisible(true);
    }//GEN-LAST:event_jMenuBuscarLavActionPerformed

    private void jMenuBuscNevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuBuscNevActionPerformed
        GUIBuscarNevera gui = new GUIBuscarNevera();
        gui.setVisible(true);
    }//GEN-LAST:event_jMenuBuscNevActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        JOptionPane.showMessageDialog(this, "Version 1.0 Alfa Agosto 2026 \n Juan Andres Bermeo Alvarez 2220241053 \n Alejandro Sanchez Quimbayo 2220241077 \n David Arredondo 2220241062");
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuDelNevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDelNevActionPerformed
        GUIEliminarNevera gui = new GUIEliminarNevera();
        gui.setVisible(true);
    }//GEN-LAST:event_jMenuDelNevActionPerformed

    private void jMenuDelLavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDelLavActionPerformed
        GUIEliminarLavadora gui = new GUIEliminarLavadora();
        gui.setVisible(true);

    }//GEN-LAST:event_jMenuDelLavActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        GUIActualizarLavadora gui = new GUIActualizarLavadora();
        gui.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        GUIActualizarNevera gui = new GUIActualizarNevera();
        gui.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        GUIAddProgramaLavado gui = new GUIAddProgramaLavado();
        gui.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        GUIActualizarProgramaLavado gui = new GUIActualizarProgramaLavado();
        gui.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        GUIBuscarProgramaLavado gui = new GUIBuscarProgramaLavado();
        gui.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        GUIListarProgramaLavado gui = new GUIListarProgramaLavado();
        gui.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        GUIEliminarProgramaLavado gui = new GUIEliminarProgramaLavado();
        gui.setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuItem jMenuAddLav;
    private javax.swing.JMenuItem jMenuAddNev;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuBuscNev;
    private javax.swing.JMenuItem jMenuBuscarLav;
    private javax.swing.JMenuItem jMenuDelLav;
    private javax.swing.JMenuItem jMenuDelNev;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuListLav;
    private javax.swing.JMenuItem jMenuListNev;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void JOptionPane() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
